[root-mount] Add userdata to physical device search. Contributes to JB#32015
In order to support flashing over standard Android filesystem layout,
accept also userdata partition as physical device target for Sailfish OS.

Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

diff --git a/sbin/root-mount b/sbin/root-mount
--- a/sbin/root-mount
+++ b/sbin/root-mount
@@ -27,15 +27,19 @@ if [ -z $1 ] || [ ! -e $1 ]; then
 	exit 1
 fi
 
-PHYSDEV=$(find-mmc-bypartlabel "sailfish")
+PHYSDEV_SEARCHLIST="sailfish sailfishos userdata"
+
+for label in $PHYSDEV_SEARCHLIST; do
+	PHYSDEV=$(find-mmc-bypartlabel "$label")
+
+	if test -n "$PHYSDEV"; then
+		break
+	fi
+done
 
 if test -z "$PHYSDEV"; then
-	# Try also legacy name "sailfishos" before failing..
-	PHYSDEV=$(find-mmc-bypartlabel "sailfishos")
-	if test -z "$PHYSDEV"; then
-		echo "root_mount: Failed to find sailfish OS partition!" > /dev/kmsg
-		exit 1
-	fi
+	echo "root_mount: Failed to find sailfish OS partition!" > /dev/kmsg
+	exit 1
 fi
 
 ROOTDEV="/dev/sailfish/root"
