[initrd] Add support for factory reset. Contributes to JB#27238
Simple factory reset from squashfs images in fimage partition. Firmware
flashing is not yet supported in this, only root & home recovery.

Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

diff --git a/sbin/root-mount b/sbin/root-mount
--- a/sbin/root-mount
+++ b/sbin/root-mount
@@ -26,9 +26,9 @@ find_device_bypartlabel()
 		echo "root_mount: find_partlabel_device: Error, no label name given!" > /dev/kmsg
 		exit 1
 	fi
-	for i in $(ls -d /sys/class/block/mmcblk0p*); do
-		if cat $i/uevent | grep PARTNAME=$1 > /dev/null; then
-			FIMAGE_DEV_NAME=$(echo $i | cut -d "/" -f 5)
+	for mmc_sysfs in $(ls -d /sys/class/block/mmcblk0p*); do
+		if cat $mmc_sysfs/uevent | grep PARTNAME=$1 > /dev/null; then
+			FIMAGE_DEV_NAME=$(echo $mmc_sysfs | cut -d "/" -f 5)
 			echo "/dev/$FIMAGE_DEV_NAME"
 			return 0
 		fi
@@ -45,6 +45,7 @@ fi
 PHYSDEV=$(find_device_bypartlabel "sailfishos")
 ROOTDEV="/dev/sailfish/root"
 HOMEDEV="/dev/sailfish/home"
+MOUNT_POINT=$1
 
 # Amount of space to keep unallocated for refilling root or home later on.
 # Please keep this multiple of 500MB
@@ -111,18 +112,86 @@ check_firstboot_resize()
 	fi
 }
 
+flash_firmwares()
+{
+	echo "root_mount: TODO, IMPLEMENT FIRMWARE FLASHING" > /dev/kmsg
+}
 
+reset_factory_image()
+{
+	echo "root_mount: Running factory reset" > /dev/kmsg
+	FIMAGE_DEV_PATH=$(find_device_bypartlabel "fimage")
+	echo "root_mount: fimage partition in $FIMAGE_DEV_PATH" > /dev/kmsg
+
+	FIMAGE_MOUNT=$(mktemp -d)
+	if mount "$FIMAGE_DEV_PATH" "$FIMAGE_MOUNT"; then
+		umount $MOUNT_POINT/home
+		umount $MOUNT_POINT
+		lvm vgchange -a n
+		lvm vgremove -y sailfish
+		lvm pvremove -y $PHYSDEV
+		lvm pvcreate $PHYSDEV
+		lvm vgcreate sailfish $PHYSDEV
+		lvm lvcreate -L "$ROOT_SIZE"M --name root sailfish
+		# TODO: maybe figure out something better than 1G size here
+		lvm lvcreate -L 1G --name home sailfish
+		mkfs.ext4 $ROOTDEV
+		mkfs.ext4 $HOMEDEV
+		check_firstboot_resize
+		mount $ROOTDEV $MOUNT_POINT
+		mkdir -p $MOUNT_POINT/home
+		mount $HOMEDEV $MOUNT_POINT/home
+		TEMPMOUNT=$(mktemp -d)
+		# Find the biggest versioned Sailfish folder and use that
+		SAILFISH_FIMAGE=$(ls -d $FIMAGE_MOUNT/Sailfish* | tail -1)
+		mount -t squashfs -o loop $SAILFISH_FIMAGE/sailfish_root.squashfs.img $TEMPMOUNT
+		cp -a $TEMPMOUNT/* $MOUNT_POINT
+		sync
+		umount $TEMPMOUNT
+		mount -t squashfs -o loop $SAILFISH_FIMAGE/sailfish_home.squashfs.img $TEMPMOUNT
+		cp -a $TEMPMOUNT/* $MOUNT_POINT/home
+		sync
+		umount $TEMPMOUNT
+		rmdir $TEMPMOUNT
+		flash_firmwares
+	else
+		echo "root_mount: Error, could not mount fimage for factory reset!" > /dev/kmsg
+		rmdir $FIMAGE_MOUNT
+		return
+	fi
+	sync
+	umount $FIMAGE_MOUNT
+	rmdir $FIMAGE_MOUNT
+	poweroff -f
+}
+
+# If mounted filesystem $1 has .clear-device file, reset factory image.
+factory_reset_if_needed()
+{
+	if test -f $1/usr/share/lipstick/devicelock/.clear-device; then
+		reset_factory_image
+	fi
+}
 
 # Make sure all of the disk is assigned for use
 lvm pvresize $PHYSDEV
+
 # Activate LVs on sailfish volume group
-lvm vgchange -a y
+if ! lvm vgchange -a y sailfish; then
+	# TODO: Consider doing a factory reset here instead of aborting...
+	#reset_factory_image
+	echo "root_mount: No sailfish VG found, aborting!" > /dev/kmsg
+	exit 1
+fi
+
+# Check factory reset need.
+if mount -t ext4 $ROOTDEV $1; then
+	factory_reset_if_needed $1
+	umount $1
+fi
 
 # Check and resize root and home in case usage indicates first boot
 check_firstboot_resize
-
-# create home dir to target
-mkdir -p $1/home
 
 # TODO: revisit for encryption, where home would not be mounted here.
 if (mount -t ext4 $ROOTDEV $1 && mount -t ext4 $HOMEDEV $1/home); then
