[initrd] Support normal "sailfish" partition label. Contributes to JB#29962
In order to be able to softly change Sailfish OS main partition label
as the normal "sailfish" from current "sailfishos" let's add a check
to support both labels for now.

Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

diff --git a/sbin/root-mount b/sbin/root-mount
--- a/sbin/root-mount
+++ b/sbin/root-mount
@@ -26,7 +26,17 @@ if [ -z $1 ] || [ ! -e $1 ]; then
 	exit 1
 fi
 
-PHYSDEV=$(find-mmc-bypartlabel "sailfishos")
+PHYSDEV=$(find-mmc-bypartlabel "sailfish")
+
+if test -z "$PHYSDEV"; then
+	# Try also legacy name "sailfishos" before failing..
+	PHYSDEV=$(find-mmc-bypartlabel "sailfishos")
+	if test -z "$PHYSDEV"; then
+		echo "root_mount: Failed to find sailfish OS partition!" > /dev/kmsg
+		exit 1
+	fi
+fi
+
 ROOTDEV="/dev/sailfish/root"
 HOMEDEV="/dev/sailfish/home"
 MOUNT_POINT=$1
