[initrd] Open shell option in recovery menu. Contributes to JB#25121
The device lock check is not working currently. Disabling the check
for shell option to enable easier debugging and development of
recovery mode. This should be reverted before final release.

Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

diff --git a/usr/bin/recovery-menu b/usr/bin/recovery-menu
--- a/usr/bin/recovery-menu
+++ b/usr/bin/recovery-menu
@@ -562,7 +562,9 @@ do
       echo
       echo -n "If you continue, this may void your warranty. Are you really SURE? "
       if prompty "[y/N]"; then
-        call_devlock_action shell || error_exit_and_cleanup
+        # call_devlock_action shell || error_exit_and_cleanup
+        # HACK: just run shell for now.
+        sh || error_exit_and_cleanup
         sync
       fi
       ;;
