[recovery] Move common code to recovery-functions.sh. Contributes to JB#30614
Move echo_err() from recovery-menu and recovery-menu-devicelock scripts
to recovery-functions.sh script. This file will contain common functions.

Move "set -e" to the top to be the first command of the recovery-menu script.

Signed-off-by: Igor Zhbanov <igor.zhbanov@jolla.com>

diff --git a/usr/bin/recovery-menu b/usr/bin/recovery-menu
--- a/usr/bin/recovery-menu
+++ b/usr/bin/recovery-menu
@@ -22,6 +22,11 @@
 #
 ##############################################################################
 
+# Exit immediately if a command fails
+set -e
+
+. /usr/bin/recovery-functions.sh
+
 DEVICELOCK_SCRIPT_ABS_PATH=/usr/bin/recovery-menu-devicelock
 PLUGIN=/usr/bin/restore-lock
 
@@ -30,14 +35,6 @@ if [ -f /etc/moslo-version ]; then
 else
 	VERSION="UNKNOWN"
 fi
-
-# exit immediately if a command fails
-set -e
-
-echo_err()
-{
-	echo "$@" 1>&2
-}
 
 # umount_and_delete will umount and rm the dir which is passed as ARGUMENT
 # Arguments: 1 dir
